# Generated by Django 2.2.7 on 2019-11-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestScrapyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('spider_name', models.CharField(max_length=255)),
                ('f1', models.TextField(blank=True, null=True)),
                ('f2', models.TextField(blank=True, null=True)),
                ('f3', models.TextField(blank=True, null=True)),
                ('f4', models.TextField(blank=True, null=True)),
                ('f5', models.TextField(blank=True, null=True)),
                ('f6', models.TextField(blank=True, null=True)),
                ('f7', models.TextField(blank=True, null=True)),
                ('f8', models.TextField(blank=True, null=True)),
                ('f9', models.TextField(blank=True, null=True)),
                ('f10', models.TextField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('site', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
