# Generated by Django 2.2.6 on 2019-11-03 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseScrapyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f1', models.TextField(blank=True, null=True)),
                ('f2', models.TextField(blank=True, null=True)),
                ('f3', models.TextField(blank=True, null=True)),
                ('f4', models.TextField(blank=True, null=True)),
                ('f5', models.TextField(blank=True, null=True)),
                ('f6', models.TextField(blank=True, null=True)),
                ('f7', models.TextField(blank=True, null=True)),
                ('f8', models.TextField(blank=True, null=True)),
                ('f9', models.TextField(blank=True, null=True)),
                ('f10', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestScrapyModel',
            fields=[
                ('basescrapymodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scrapyitem.BaseScrapyModel')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
            ],
            bases=('scrapyitem.basescrapymodel',),
        ),
    ]
